version: "3.11"

services:
  fastcampus:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.integrated
    image: fastcampus
    container_name: fastcampus_dev

    # 호스트 사용자와 컨테이너 사용자 동기화
    user: "${UID}:${GID}"

    # 프로젝트 폴더만 마운트 (홈 디렉터리 제외하여 호스트 설정 간섭 방지)
    volumes:
      - .:/workspaces/fastcampus
    working_dir: /workspaces/fastcampus

    # 포트 포워딩
    ports:
      - "8080:8080" # MCP Server (HTTP transport)

    # 환경변수 설정
    environment:
      - HOME=/home/vscode
      - MCP_SERVER_PORT=8080
      - NODE_VERSION=22
      - NVM_DIR=/home/vscode/.nvm
      - SECURITY_LAB_MODE=enabled
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1

    # 컨테이너와 상호작용을 위한 인터랙티브 세션 활성화
    stdin_open: true
    tty: true

    # 추가 런타임 인자 (보안 실습을 위한 설정)
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
